[project]
name = "homework-04"
version = "0.1.0"
description = "Асинхронное программирование и API"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "SQLAlchemy>=1.4",
#    "aiohttp"
]
